image: "registry.gitlab.e.foundation:5000/e/apps/docker-android-apps-cicd:latest"

stages:
- build
- .post

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  stage: build
  script:
  - ./gradlew assemble
  artifacts:
    paths:
    - app/build/outputs/aar

deploy:
  stage: .post
  script:
    - 'gradle publish'
  only:
    - main

